// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4JwY7cb9kw_Zk6_m5p4fm2QRBZtk0eak',
    appId: '1:406970501510:web:7798873b973c6238f9c407',
    messagingSenderId: '406970501510',
    projectId: 'bluetoothbeacon-99e3e',
    authDomain: 'bluetoothbeacon-99e3e.firebaseapp.com',
    storageBucket: 'bluetoothbeacon-99e3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANQD1uEkrKURWm1-pxyGhXbS2x8zt-a08',
    appId: '1:406970501510:android:befaf81c29e419d4f9c407',
    messagingSenderId: '406970501510',
    projectId: 'bluetoothbeacon-99e3e',
    storageBucket: 'bluetoothbeacon-99e3e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vUg3r23_t5aAwnUBlIdincWqXJGOlKI',
    appId: '1:406970501510:ios:825349e92fe52219f9c407',
    messagingSenderId: '406970501510',
    projectId: 'bluetoothbeacon-99e3e',
    storageBucket: 'bluetoothbeacon-99e3e.firebasestorage.app',
    iosBundleId: 'com.example.smartattendancebeacon',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vUg3r23_t5aAwnUBlIdincWqXJGOlKI',
    appId: '1:406970501510:ios:825349e92fe52219f9c407',
    messagingSenderId: '406970501510',
    projectId: 'bluetoothbeacon-99e3e',
    storageBucket: 'bluetoothbeacon-99e3e.firebasestorage.app',
    iosBundleId: 'com.example.smartattendancebeacon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4JwY7cb9kw_Zk6_m5p4fm2QRBZtk0eak',
    appId: '1:406970501510:web:fa5119f56202e3f8f9c407',
    messagingSenderId: '406970501510',
    projectId: 'bluetoothbeacon-99e3e',
    authDomain: 'bluetoothbeacon-99e3e.firebaseapp.com',
    storageBucket: 'bluetoothbeacon-99e3e.firebasestorage.app',
  );

}